### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by arturoovf** [Mola19/openrgb-sdk#4]
I use Homebridge openrgb plug-in, and with the addition of a new device (Adata s40g) I got this error from the logs:

```
[12/3/2021, 11:40:00 PM] Homebridge v1.3.8 (HAP v0.9.7) (OpenRGB) is running on port 54244.

/homebridge/node_modules/homebridge-openrgb/node_modules/openrgb-sdk/src/device.js:79
                flagcheck = Array(8 - flagcheck.length).concat(flagcheck.split("")).reverse()
              ^
RangeError: Invalid array length
    at readModes (/homebridge/node_modules/homebridge-openrgb/node_modules/openrgb-sdk/src/device.js:79:15)
    at new Device (/homebridge/node_modules/homebridge-openrgb/node_modules/openrgb-sdk/src/device.js:21:46)
    at Client.getControllerData (/homebridge/node_modules/homebridge-openrgb/node_modules/openrgb-sdk/src/client.js:78:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at OpenRgbPlatform.rgbConnection (/homebridge/node_modules/homebridge-openrgb/src/platform.ts:229:33)
    at OpenRgbPlatform.discoverDevices (/homebridge/node_modules/homebridge-openrgb/src/platform.ts:102:7)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-openrgb/src/platform.ts:68:9)
[12/3/2021, 11:40:00 PM] [OpenRGB] Child bridge process ended
[12/3/2021, 11:40:00 PM] [OpenRGB] Process Ended. Code: 1, Signal: null`
```

I was told by plug-in developer that the error is coming from the sdk so I should report it here

**Comment by Mola19** [comment]
issue solved at: https://github.com/DallasHoff/homebridge-openrgb/issues/3
